etip/etip/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('restful_api.urls')),
    path('stats/', include('stats.urls')),
    path('', include('trackers.urls')),
]

etip/trackers/urls.py
from django.urls import path

from . import views

app_name = 'trackers'
urlpatterns = [
    path('', views.home, name='home'),
    path('trackers/all', views.index, name='index'),
    path('trackers/review', views.review, name='review'),
    path('trackers/approved', views.approved, name='approved'),
    path('trackers/<id>/', views.display_tracker, name='display_tracker'),
    path('trackers/<id>/approve/', views.approve, name='approve'),
    path('trackers/<id>/revoke/', views.revoke, name='revoke'),
    path('trackers/<id>/ship/', views.ship, name='ship'),
    path('trackers/<id>/needs_rework/', views.needs_rework, name='needs_rework'),
    path('trackers/<id>/needs_no_rework/', views.needs_no_rework, name='needs_no_rework'),
    path('trackers/export', views.export_tracker_list, name='export')
]

etip/trackers/models.py
import re
import uuid

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.db import models
from reversion.models import Version


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    is_in_exodus = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Capability(Category):
    pass


class Advertising(Category):
    pass


class Analytic(Category):
    pass


class Network(Category):
    pass


class TrackerCategory(Category):
    pass


class Tracker(models.Model):
    MIN_SIGNATURE_SIZE = 4
    MIN_DESCRIPTION_SIZE = 180
    MIN_WEBSITE_SIZE = 3

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(unique=True, max_length=200)
    description = models.TextField(blank=True)
    creation_date = models.DateField(auto_now_add=True)
    code_signature = models.CharField(max_length=500, default='', blank=True)
    network_signature = models.CharField(
        max_length=500, default='', blank=True)
    website = models.URLField()
    category = models.ManyToManyField(TrackerCategory, blank=True)
    is_in_exodus = models.BooleanField(default=False)
    api_key_ids = models.CharField(max_length=1000, default='', blank=True)
    documentation = models.CharField(max_length=1000, default='', blank=True)
    capability = models.ManyToManyField(Capability, blank=True)
    advertising = models.ManyToManyField(Advertising, blank=True)
    analytic = models.ManyToManyField(Analytic, blank=True)
    network = models.ManyToManyField(Network, blank=True)
    maven_repository = models.CharField(max_length=500, default='', blank=True)
    artifact_id = models.CharField(max_length=500, default='', blank=True)
    group_id = models.CharField(max_length=500, default='', blank=True)
    gradle = models.CharField(max_length=500, default='', blank=True)
    comments = models.TextField(blank=True)
    exodus_matches = models.PositiveIntegerField(blank=True, null=True)
    needs_rework = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_fields(self):
        return [
            (field.name, field.value_to_string(self))
            for field in Tracker._meta.fields
        ]

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)

        if self.documentation:
            links = self.documentation.split(' ')
            validate = URLValidator()
            for link in links:
                try:
                    validate(link)
                except ValidationError:
                    raise ValidationError(
                        {
                            'documentation':
                            f'Invalid URL: {link} (space-separated list).'
                        }
                    )

        spaces_errors = []
        if ' ' in self.code_signature:
            spaces_errors.append('code_signature')
        if ' ' in self.network_signature:
            spaces_errors.append('network_signature')
        if spaces_errors:
            raise ValidationError(
                {err: "Must not contain spaces." for err in spaces_errors})

        regex_errors = []
        try:
            re.compile(self.code_signature)
        except re.error:
            regex_errors.append('code_signature')
        try:
            re.compile(self.network_signature)
        except re.error:
            regex_errors.append('network_signature')
        if regex_errors:
            raise ValidationError(
                {err: "Must be a valid regex." for err in regex_errors})

    def has_any_signature_collision(self):
        trackers = Tracker.objects.all().exclude(id=self.id)
        for t in trackers:
            if self._has_same_code_signature(t) \
                    or self._has_same_network_signature(t):
                return True
        return False

    def get_trackers_with_code_signature_collision(self):
        collisions = []
        trackers = Tracker.objects.all().exclude(id=self.id)
        for t in trackers:
            if self._has_same_code_signature(t):
                collisions.append(t)
        return collisions

    def get_trackers_with_network_signature_collision(self):
        collisions = []
        trackers = Tracker.objects.all().exclude(id=self.id)
        for t in trackers:
            if self._has_same_network_signature(t):
                collisions.append(t)
        return collisions

    def _has_same_network_signature(self, tracker):
        return re.search(self.network_signature, tracker.network_signature) \
            and len(self.network_signature) > self.MIN_SIGNATURE_SIZE

    def _has_same_code_signature(self, tracker):
        return re.search(self.code_signature, tracker.code_signature) \
            and len(self.code_signature) > self.MIN_SIGNATURE_SIZE

    def progress(self):
        p = 0
        if self.category.count() > 0:
            p += 15
        if len(self.description) >= self.MIN_DESCRIPTION_SIZE:
            p += 15
        if len(self.code_signature) >= self.MIN_SIGNATURE_SIZE:
            p += 10
        if len(self.network_signature) >= self.MIN_SIGNATURE_SIZE:
            p += 10
        if len(self.website) >= self.MIN_WEBSITE_SIZE:
            p += 10
        if self.capability.count() > 0:
            p += 10
        if self.analytic.count() > 0:
            p += 10
        if self.advertising.count() > 0:
            p += 10
        if self.network.count() > 0:
            p += 6
        if self.maven_repository:
            p += 1
        if self.artifact_id:
            p += 1
        if self.group_id:
            p += 1
        if self.gradle:
            p += 1
        return p

    def missing_fields(self):
        missing = []
        if self.category.count() == 0:
            missing.append('Categories')
        if len(self.description) < self.MIN_DESCRIPTION_SIZE:
            missing.append('Description')
        if len(self.code_signature) < self.MIN_SIGNATURE_SIZE:
            missing.append('Code signature')
        if len(self.network_signature) < self.MIN_SIGNATURE_SIZE:
            missing.append('Network signature')
        if len(self.website) < self.MIN_WEBSITE_SIZE:
            missing.append('Website')
        if self.capability.count() == 0:
            missing.append('Capabilities')
        if self.analytic.count() == 0:
            missing.append('Analytics')
        if self.advertising.count() == 0:
            missing.append('Advertising')
        if self.network.count() == 0:
            missing.append('Networks')
        if not self.maven_repository:
            missing.append('Maven repository')
        if not self.artifact_id:
            missing.append('Artifact ID')
        if not self.group_id:
            missing.append('Group ID')
        if not self.gradle:
            missing.append('Gradle')
        return missing

    def approvers(self):
        approvals = self.approvals.all()
        return [approval.approver.username for approval in approvals]

    def creator(self):
        versions = Version.objects.get_for_object(self)
        if len(versions) > 0:
            return versions[len(versions) - 1].revision.user
        else:
            return None

    def documentation_list(self):
        if self.documentation:
            documentation_list = self.documentation.split(' ')
        else:
            documentation_list = []
        return documentation_list

    def status(self):
        if self.is_in_exodus:
            return 'In εxodus'
        if self.needs_rework:
            return 'Needs rework'
        if not self.code_signature:
            return 'Missing signature'
        if self.exodus_matches is None:
            return 'Not analyzed'
        if self.exodus_matches == 0:
            return 'Unmatched in εxodus'

        if self.approvals.count() < 2:
            return 'Waiting for review'

        return 'Approved'

    def status_color_class(self):
        if self.status() == 'In εxodus':
            return 'badge-success'
        if self.status() == 'Approved':
            return 'badge-info'
        if self.status() == 'Waiting for review':
            return 'badge-warning'

        return 'badge-danger'

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'code_signature': self.code_signature,
            'network_signature': self.network_signature,
            'website': self.website,
            'category': [c.name for c in self.category.all()],
            'is_in_exodus': self.is_in_exodus,
            'documentation': self.documentation_list()
        }


class TrackerApproval(models.Model):
    tracker = models.ForeignKey(
        Tracker, related_name='approvals', on_delete=models.CASCADE,)
    approver = models.ForeignKey(
        User, related_name='trackers_approval', on_delete=models.CASCADE,)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (("tracker", "approver"),)

etip/trackers/views.py
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.http.response import Http404
from django.shortcuts import redirect, render
import reversion

from .models import Tracker, TrackerApproval


def home(request):
    return render(request, 'home.html')


def index(request):
    try:
        # TODO: Use a Django Form instead ?
        filter_name = request.GET.get('tracker_name', '')
        only_collisions = request.GET.get('only_collisions', False)
        approve_select = request.GET.get('approve_select', '')
        trackers_select = request.GET.get('trackers_select', '')
        if filter_name:
            trackers = Tracker.objects.filter(name__startswith=filter_name)
        else:
            trackers = Tracker.objects

        trackers = trackers.order_by('name')

        if trackers_select == "exodus":
            trackers = trackers.filter(is_in_exodus=True)
        elif trackers_select == "etip":
            trackers = trackers.filter(is_in_exodus=False)

        if only_collisions:
            trackers = list(
                t for t in trackers if t.has_any_signature_collision()
            )

        if approve_select == "approved":
            trackers = list(
                t for t in trackers if t.approvals.count() >= 2
            )
        elif approve_select == "need_review":
            trackers = list(
                t for t in trackers if t.approvals.count() == 1
            )
        elif approve_select == "no_approvals":
            trackers = list(
                t for t in trackers if t.approvals.count() == 0
            )

        count = len(trackers)

        paginator = Paginator(trackers, 20)
        page = request.GET.get('page', 1)
        trackers = paginator.get_page(page)
    except Tracker.DoesNotExist:
        raise Http404("trackers does not exist")

    return render(request, 'tracker_list.html', {
        'trackers': trackers,
        'count': count,
        'filter_name': filter_name,
        'only_collisions': 'checked' if only_collisions else '',
        'approve_select': approve_select,
        'trackers_select': trackers_select
    })


def display_tracker(request, id):
    try:
        tracker = Tracker.objects.get(pk=id)
    except (Tracker.DoesNotExist, ValidationError):
        raise Http404("Tracker does not exist")

    return render(request, 'tracker.html', {'tracker': tracker})


def review(request):
    try:
        trackers = Tracker.objects.filter(is_in_exodus=False).order_by('-exodus_matches', 'name')
        trackers = list(t for t in trackers if t.approvals.count() == 1)

        count = len(trackers)

        paginator = Paginator(trackers, 20)
        page = request.GET.get('page', 1)
        trackers = paginator.get_page(page)
    except Tracker.DoesNotExist:
        raise Http404("trackers does not exist")

    return render(request, 'tracker_review.html', {
        'title': 'Waiting for review',
        'trackers': trackers,
        'count': count,
    })


def approved(request):
    try:
        trackers = Tracker.objects.filter(is_in_exodus=False).order_by('-exodus_matches', 'name')
        trackers = list(t for t in trackers if t.approvals.count() >= 2)

        count = len(trackers)

        paginator = Paginator(trackers, 20)
        page = request.GET.get('page', 1)
        trackers = paginator.get_page(page)
    except Tracker.DoesNotExist:
        raise Http404("trackers does not exist")

    return render(request, 'tracker_review.html', {
        'title': 'Approved trackers',
        'trackers': trackers,
        'count': count,
    })


def export_tracker_list(request):
    trackers = Tracker.objects.order_by('name')
    trackers_list = [tracker.serialize() for tracker in trackers]
    response = JsonResponse(dict(trackers=trackers_list))
    response['Content-Disposition'] = 'attachment; filename=trackers.json'
    return response


def approve(request, id):
    if request.method != 'POST':
        return redirect('/')

    if not request.user.is_authenticated:
        raise PermissionDenied

    try:
        tracker = Tracker.objects.get(pk=id)
    except (Tracker.DoesNotExist, ValidationError):
        raise Http404("Tracker does not exist")

    if tracker.creator() and request.user == tracker.creator():
        raise PermissionDenied

    approval = TrackerApproval(
        tracker=tracker,
        approver=request.user
    )
    approval.save()
    return redirect(f'/trackers/{tracker.id}')


def revoke(request, id):
    if request.method != 'POST':
        return redirect('/')

    if not request.user.is_authenticated:
        raise PermissionDenied

    try:
        tracker = Tracker.objects.get(pk=id)
    except (Tracker.DoesNotExist, ValidationError):
        raise Http404("Tracker does not exist")

    approval = TrackerApproval.objects.get(
        tracker=tracker,
        approver=request.user
    )
    approval.delete()
    return redirect(f'/trackers/{tracker.id}')


def ship(request, id):
    if request.method != 'POST':
        return redirect('/')

    if not request.user.is_authenticated or not request.user.is_superuser:
        raise PermissionDenied

    try:
        tracker = Tracker.objects.get(pk=id)
    except (Tracker.DoesNotExist, ValidationError):
        raise Http404("Tracker does not exist")

    with reversion.create_revision():
        tracker.is_in_exodus = True
        tracker.save()

        reversion.set_user(request.user)
        reversion.set_comment("Shipped to exodus")

    return redirect(f'/trackers/{tracker.id}')


def needs_rework(request, id):
    if request.method != 'POST':
        return redirect('/')

    if not request.user.is_authenticated or not request.user.is_superuser:
        raise PermissionDenied

    try:
        tracker = Tracker.objects.get(pk=id)
    except (Tracker.DoesNotExist, ValidationError):
        raise Http404("Tracker does not exist")

    with reversion.create_revision():
        tracker.needs_rework = True
        tracker.save()

        reversion.set_user(request.user)
        reversion.set_comment("Set as 'needs rework'")

    return redirect(f'/trackers/{tracker.id}')


def needs_no_rework(request, id):
    if request.method != 'POST':
        return redirect('/')

    if not request.user.is_authenticated or not request.user.is_superuser:
        raise PermissionDenied

    try:
        tracker = Tracker.objects.get(pk=id)
    except (Tracker.DoesNotExist, ValidationError):
        raise Http404("Tracker does not exist")

    with reversion.create_revision():
        tracker.needs_rework = False
        tracker.save()

        reversion.set_user(request.user)
        reversion.set_comment("Set as 'rework was done'")

    return redirect(f'/trackers/{tracker.id}')

etip/trackers/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <!-- style sheet for account -->
  <link rel="stylesheet" href="{% static 'css/account.css' %}">

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
  <style>
    html {
      font-size : 0.9em;
    }
    .tooltip-inner {
      text-align: left;
    }
    thead {
      font-weight: bold;
      font-size : 1.1em;
    }
  </style>
  <title>ETIP - εxodus</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
      <span class="h2">ETIP</span> <span class="small text-muted">v1.12</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Trackers
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'trackers:index' %}">All trackers</a>
            <a class="dropdown-item" href="{% url 'trackers:review' %}">Waiting for second review</a>
            <a class="dropdown-item" href="{% url 'trackers:approved' %}">Approved</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'admin:trackers_tracker_add' %}">Add new tracker</a>
          </div>
        </li>
      </ul>
      <div class="ml-auto">
        <a class="btn btn-light btn-sm mr-lg-1 ml-lg-1" href="{% url 'admin:login' %}" role="button">{% if not user.is_authenticated %}Login{% else %}Admin{% endif %}</a>
      </div>
    </div>
  </nav>
  <br>
  <div class="container-fluid">
    <div class="row justify-content-md-center">
      {% if not user.is_authenticated %}
        <div class="col-xl-10 col-12">
          <div class="alert alert-info">
            ℹ️&nbsp;&nbsp;You need to be logged in to <b>add a new tracker</b> or <b>edit existing ones</b> -
            <a target="_blank" rel="noreferrer" href="https://github.com/Exodus-Privacy/etip/#contribute-to-the-identification-of-trackers">
              More details
            </a>
          </div>
        </div>
      {% endif %}

      {% block content %}

      {% endblock %}
    </div>
  </div>
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
  {% block scripts %}
  {% endblock %}
</body>
</html>

etip/trackers/templates/home.html
{% extends "base.html"%}
{% block content %}
<div class="col-xl-10 col-12">
  <h2 class="text-center">
    Welcome to
    <b>E</b>xodus
    <b>T</b>racker
    <b>I</b>nvestigation
    <b>P</b>latform
  </h2>
</div>
<div class="col-xl-10 col-12">
  <h3 class="mt-4">What is ETIP?</h3>
  <p>ETIP is meant to ease investigations on tracker detection for the platform <a target="_blank"
      href="https://reports.exodus-privacy.eu.org">εxodus</a>.</p>
  <p>It offers the following features:</p>
  <ul>
    <li>track all modifications on trackers</li>
    <li>detect rules collisions for both network and code signature</li>
  </ul>
</div>
<div class="col-xl-10 col-12">
  <h3 class="mt-4">How to contribute?</h3>
  <p>If you wish to help us identify new trackers, you can easily <a target="_blank" rel="noreferrer"
      href="https://github.com/Exodus-Privacy/etip/#contribute-to-the-identification-of-trackers">request an ETIP
      account</a>.</p>
  <p>Once you have an account, you can:</p>
  <div class="row">
    <div class="col-12 col-md-4 mb-4 text-center">
      <p>Create new trackers profiles</p>
      <a class="btn btn-primary" href="{% url 'admin:trackers_tracker_add' %}" role="button">Create new tracker</a>
    </div>
    <div class="col-12 col-md-4 mb-4 text-center">
      <p>Extend the content of existing trackers profiles</p>
      <a class="btn btn-primary" href="{% url 'trackers:index' %}" role="button">See all trackers</a>
    </div>
    <div class="col-12 col-md-4 mb-4 text-center">
      <p>Review trackers before they are sent to εxodus</p>
      <a class="btn btn-primary" href="{% url 'trackers:review' %}" role="button">Review trackers</a>
    </div>
  </div>
</div>
<div class="col-xl-10 col-12">
  <h3 class="mt-4">Curious about ETIP?</h3>
  <p>ETIP is free and open source, feel free to check <a target="_blank" rel="noreferrer"
      href="https://github.com/Exodus-Privacy/etip/">its GitHub page</a>.</p>
</div>
{% endblock %}

etip/trackers/templates/tracker_list.html
{% extends "base.html"%}
{% load url_replace %}
{% block content %}
  <div class="col-xl-10 col-12">
    <h2>
      All trackers <span class="badge badge-info">{{ count }}</span>
    </h2>
  </div>

  <div class="col-xl-10 col-12">
    <form class="form-inline" method="get">
      <label class="sr-only" for="inlineFormTrackerName">Tracker name:</label>
      <input type="text" class="form-control mb-2 mr-2 col-3" value="{{ filter_name }}" name="tracker_name" id="inlineFormTrackerName" placeholder="Tracker name">
      <div class="form-row mb-2 ml-sm-2 mr-sm-2">
        <select class="custom-select" id="trackers_select" name="trackers_select">
          <option value="" selected disabled>In εxodus?</option>
          <option value="all" {% if trackers_select == "all" %}selected{% endif %}>All trackers</option>
          <option value="exodus" {% if trackers_select == "exodus" %}selected{% endif %}>In εxodus</option>
          <option value="etip" {% if trackers_select == "etip" %}selected{% endif %}>Only in ETIP</option>
        </select>
      </div>
      <div class="form-row mb-2 ml-sm-2 mr-sm-2">
        <select class="custom-select" id="approve_select" name="approve_select">
          <option value="" selected disabled>Approved?</option>
          <option value="all" {% if approve_select == "all" %}selected{% endif %}>All trackers</option>
          <option value="no_approvals" {% if approve_select == "no_approvals" %}selected{% endif %}>No approvals</option>
          <option value="need_review" {% if approve_select == "need_review" %}selected{% endif %}>Need 2nd review</option>
          <option value="approved" {% if approve_select == "approved" %}selected{% endif %}>Approved</option>
        </select>
      </div>
      <div class="form-check mb-2 mr-sm-2">
        <input type="checkbox" class="form-check-input" id="onlyCollisionCheckbox" name="only_collisions" {{ only_collisions }}/>
        <label class="form-check-label" for="onlyCollisionCheckbox">With collisions</label>
      </div>
      <button type="submit" class="btn btn-primary mb-2 mr-2">Submit</button>
      <a class="btn btn-info mb-2" href={% url 'trackers:index' %}>Clear filter</a>
    </form>
  </div>

  <div class="col-xl-10 col-12">
    {% if trackers %}
      <div class="alert-heading">
        <a href="{% url 'trackers:export' %}">Export all trackers</a>
      </div>
      <table class="table table-hover">
        <thead class="">
          <tr>
            <td scope="col">Name</td>
            <td scope="col">Status</td>
            <td scope="col">Website</td>
            <td scope="col">Category</td>
            <td scope="col">Code signature</td>
            <td scope="col">Network signature</td>
          </tr>
        </thead>
        <tbody>
          {% for tracker in trackers %}
            <tr>
              <td>
                <a href="{% url 'trackers:display_tracker' tracker.id %}">
                  <strong>{{ tracker.name }}</strong>
                </a>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: {{ tracker.progress }}%"
                       aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"  data-toggle="tooltip" data-placement="right"  data-html="true" title="
                      Missing fields:
                      <ul>
                          {% for f in tracker.missing_fields %}
                            <li>{{f}}</li>
                          {% endfor %}
                      </ul>
                    ">
                  </div>
                </div>
              </td>
              <td>
                <span class="badge {{ tracker.status_color_class }}">
                  <b>{{ tracker.status }}</b>
                </span>
              </td>
              <td>
                <a target="_blank" rel="noreferrer" href="{{ tracker.website }}">www</a>
              </td>
              <td>
                {% for c in tracker.category.all %}
                  <span class="badge badge-primary">{{ c.name }}</span>
                {% endfor %}
              </td>
              <td>
                <code>{{ tracker.code_signature|truncatechars:36 }}</code>
                {% if tracker.get_trackers_with_code_signature_collision %}
                  <div class="alert alert-warning">
                    <strong>⚠️</strong> <b>Collision detected</b> with:
                    <ul>
                      {% for c in tracker.get_trackers_with_code_signature_collision %}
                        <li><a href="{% url 'trackers:display_tracker' c.id %}">{{ c }}</a></li>
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
              </td>
              <td>
                <code>{{ tracker.network_signature|truncatechars:36 }}</code>
                {% if tracker.get_trackers_with_network_signature_collision %}
                  <div class="alert alert-warning">
                    <strong>⚠️</strong> <b>Collision detected</b> with:
                    <ul>
                      {% for c in tracker.get_trackers_with_network_signature_collision %}
                        <li><a href="{% url 'trackers:display_tracker' c.id %}">{{ c }}</a></li>
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div>
        <ul class="pagination pagination-sm justify-content-center">
          {% if trackers.has_previous %}
            <li class="page-item"><a class="page-link" href="?{% url_replace 'page' 1 %}">First</a></li>
            <li class="page-item"><a class="page-link" href="?{% url_replace 'page' trackers.previous_page_number %}">Previous</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
          {% endif %}
          {% for i in trackers.paginator.page_range %}
            {% if i > trackers.number|add:'-5' and i < trackers.number|add:'5' %}
              {% if i == trackers.number %}
                <li class="page-item active"> <a class="page-link" href="?{% url_replace 'page' i %}">{{ i }}</a> </li>
              {% else %}
                <li class="page-item"> <a class="page-link" href="?{% url_replace 'page' i %}">{{ i }}</a> </li>
              {% endif %}
            {% endif %}
          {% endfor %}
          {% if trackers.has_next %}
            <li class="page-item"><a class="page-link" href="?{% url_replace 'page' trackers.next_page_number %}">&nbsp&nbspNext&nbsp&nbsp</a></li>
            <li class="page-item"><a class="page-link" href="?{% url_replace 'page' trackers.paginator.num_pages %}">Last&nbsp</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">&nbsp&nbspNext&nbsp&nbsp</a></li>
            <li class="page-item disabled"><a class="page-link" href="">Last&nbsp</a></li>
          {% endif %}
        </ul>
      </div>
    {% else %}
      <p>No trackers are available.</p>
    {% endif %}
  </div>
{% endblock %}